base_config: base
data: [ hkphi ]
repeats: 5
lr: [ 0.0001, 0.001, 0.003, 0.01, 0.03, 0.1, 0.3 ]
batch_size: [ 16 ]
image_size: [ 320 ]
models:
  network: [ unet_16_M ]
criteria:
  ce: [ ce ]
save_path: results/super-experiments/test-lr